import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 16,
    backgroundColor: "#202024",
  },
  heading: {
    fontSize: 24,
    fontWeight: "bold",
    marginBottom: 16,
  },
  profileContainer: {
    flexDirection: "column",
    alignItems: "center",
    marginBottom: 16,
    backgroundColor: "#323238",
    padding: 16,
    borderRadius: 8,
  },
  profileImage: {
    width: 100,
    height: 100,
    borderRadius: 10,
    marginBottom: 8,
  },
  profileText: {
    fontSize: 16,
    marginBottom: 4,
    color: "#C4C4CC",
    fontWeight: "bold",
  },
  buttonNovoPerfil: {
    width: "90%",
    justifyContent: "center",
    backgroundColor: "#08afa4",
    borderRadius: 4,
    paddingHorizontal: 16,
    paddingVertical: 12,
    alignSelf: "center",
    marginVertical: 10,
    alignItems: "center",
    fontWeight: "bold",
    color: "white",
    marginBottom: "30px",
  },
  buttonContainer: {
    flexDirection: "row",
    display: "flex",
    justifyContent: "center",
    fontWeight: "bold",
    backgroundColor: "",
  },
  editButton: {
    backgroundColor: "#202024",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 4,
    margin: 4,
  },
  deleteButton: {
    backgroundColor: "#dc3545",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 4,
    margin: 4,
  },
  buttonText: {
    color: "#fff",
    fontWeight: "bold",
  },
  deleteModalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    position: "absolute",
    top: "10vh",
    left: "10%",
    width: "80%",
    backgroundColor: "#202024",
    padding: 20,
    borderRadius: 10,
    zIndex: 100,
    borderWidth: 1,
  },
  deleteModal: {
    width: "80%",
    backgroundColor: "#202024",
    padding: 20,
    borderRadius: 10,
    alignItems: "center",
  },
  deleteModalText: {
    fontSize: 18,
    marginBottom: 20,
    color: "white",
  },
  cancelButton: {
    backgroundColor: "#323238",
    padding: 10,
    borderRadius: 5,
    marginHorizontal: 10,
    width: "50%",
    textAlign: "center",
    marginTop: 10,
  },
  confirmButton: {
    backgroundColor: "#08afa4",
    padding: 10,
    borderRadius: 5,
    marginHorizontal: 10,
    width: "50%",
    textAlign: "center",
  },
  buttonLabel: {
    color: "white",
    fontSize: 16,
  },
});
